server:
  port: 9001

# ApiBoot相关配置
api:
  boot:
    logging:
      admin:
        # 显示上报日志
        show-console-report-log: true
        # 格式化上报日志
        format-console-log-json: true
        # 日志上报到指定的 服务
        server-address:
    security:
      away: jdbc





# spring 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_heart_to_dream
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: a1990520
  security:
    user:
      name: my_heart_to_dream
      password: good_good_study_day_day_up

# 日志
logging:
  # 不同位置的日志级别不同
  level: debug




